---
title: "Data with scattermore2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(scattermore2)
data <- cbind(rnorm(1e5), rnorm(1e5))
```

## Colorize data with one color
```{r}
colorized <- colorize_data(data, RGBA= c(64,128,192,50), xlim=c(-5,5), ylim=c(-5,5))
raster <- rgba_int_to_raster(rgbwt_to_rgba_int(colorized))
plot(raster)
```

## Apply kernels on colorized data
```{r}
blurred_data <- apply_kernel_data(colorized)
raster <- rgba_int_to_raster(rgbwt_to_rgba_int(blurred_data))
plot(raster)
gauss_blurred_data <- apply_kernel_data(colorized, filter="gauss")
gauss_raster <- rgba_int_to_raster(rgbwt_to_rgba_int(gauss_blurred_data))
plot(gauss_raster)
```

## Colorize data with palette
```{r}
m = rep(c(0,1,2,3), each=25000)
v = c(255, 0, 0, 100, 0, 255, 0, 25, 0, 0, 255, 50, 0, 0, 0, 100)
p = array(v, c(4, 4))
colorized <- colorize_data(data, map = m, palette = p, xlim=c(-5,5), ylim=c(-5,5))
raster <- rgba_int_to_raster(rgbwt_to_rgba_int(colorized))
plot(raster)
```
