---
title: "Scatter histogram with lines"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Scatter histogram with lines}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(scattermore)
```

## Create histogram
```{r}
histogram <- scatter_lines_histogram(matrix(rnorm(40000),ncol=4,byrow=F), xlim=c(-5,5), ylim=c(-5,5))
image(histogram)
```

## Apply some kernels on histogram
```{r}
blurred_histogram <- apply_kernel_histogram(histogram, radius=4)
image(blurred_histogram)
gauss_blurred_histogram <- apply_kernel_histogram(histogram, filter="gauss", radius=4)
image(gauss_blurred_histogram)
```

## Colorize blurred histogram
```{r}
rgbwt <- histogram_to_rgbwt(blurred_histogram)
raster <- rgba_int_to_raster(rgbwt_to_rgba_int(rgbwt))
plot(raster, interpolate=F)
```

## Colorize blurred histogram with palette
```{r}
v = c(255, 0, 0, 100, 0, 255, 0, 25, 0, 0, 255, 50, 0, 0, 0, 100)
palette = array(v, c(4, 4))

rgbwt <- histogram_to_rgbwt(blurred_histogram, RGBA=palette)
raster <- rgba_int_to_raster(rgbwt_to_rgba_int(rgbwt))
plot(raster, interpolate=F)
```
